services:
  postgres:
    image: postgres:17.4
    ports:
      - 5432:5432
    env_file:
      - .env
    environment: 
      POSTGRES_DB: book_store
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}